version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

  workflow:
    jobs:
      - build
        filters:
          branches:
            only:
              - circleci
