version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
          
      - run:
          name: Install dependencies
          command: |
            npm ci
            npm run build

  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci
